name: 'Release'

run-name: Release ${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version string (semver)'
        required: true
        type: string

jobs:
  checkout:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Check for valid semver tag
        id: check_tag
        run: |
          if [[ "${{ inputs.version }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Valid tag"
            echo "name=tag_valid=true >> $GITHUB_OUTPUT"
          else
            echo "::error Invalid tag"
            echo "name=tag_valid=false >> $GITHUB_OUTPUT"
          fi

      - name: Checkout
        if: steps.check_tag.outputs.tag_valid == 'true'
        uses: actions/checkout@v4

      - name: Setup Node
        if: steps.check_tag.outputs.tag_valid == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install PNPM
        if: steps.check_tag.outputs.tag_valid == 'true'
        shell: bash
        run:
          wget -qO- https://get.pnpm.io/install.sh | ENV="$HOME/.bashrc" SHELL="$(which bash)" bash - && source /home/runner/.bashrc

      - name: Install dependencies
        if: steps.check_tag.outputs.tag_valid == 'true'
        shell: bash
        run:
          pnpm i && cd pprek24 && pnpm i
