name: 'Release'

run-name: Release ${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version string (semver)'
        required: true
        type: string

jobs:
  checkout:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Check for valid semver tag
        id: check_tag
        run: |
          if [[ "${{ inputs.version }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Valid tag"
            echo "tag_valid=true" >> $GITHUB_ENV
          else
            echo "::error Invalid tag"
            echo "tag_valid=false" >> $GITHUB_ENV
            exit 1
          fi

      - name: Checkout
        if: env.tag_valid == 'true'
        uses: actions/checkout@v4

      - name: Setup Node
        if: env.tag_valid == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install PNPM
        if: env.tag_valid == 'true'
        shell: bash
        run: |
          curl -fsSL https://get.pnpm.io/install.sh | bash -
          export PNPM_HOME="/home/runner/.local/share/pnpm"
          export PATH="$PNPM_HOME:$PATH"
          echo "PNPM_HOME=/home/runner/.local/share/pnpm" >> $GITHUB_ENV
          echo "PATH=$PNPM_HOME:$PATH" >> $GITHUB_ENV

      - name: Install dependencies
        if: env.tag_valid == 'true'
        shell: bash
        run:
          pnpm i && cd pprek24 && pnpm i

      - name: Create Realease
        if: env.tag_valid == 'true'
        shell: bash
        run:
          pnpm run create-release
